# Generated by Django 2.2.5 on 2019-09-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_auto_20190924_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.CharField(max_length=200)),
                ('familleProduit', models.CharField(max_length=200)),
                ('descriptionProduit', models.CharField(max_length=200)),
                ('quantiteMin', models.PositiveIntegerField()),
                ('packaging', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
            ],
        ),
    ]
