# Generated by Django 2.2.6 on 2019-10-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsEco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.CharField(max_length=200)),
                ('familleProduit', models.CharField(max_length=200)),
                ('descriptionProduit', models.CharField(max_length=200)),
                ('quantiteMin', models.PositiveIntegerField()),
                ('packaging', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductsMag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.CharField(max_length=200)),
                ('familleProduit', models.CharField(max_length=200)),
                ('descriptionProduit', models.CharField(max_length=200)),
                ('quantiteMin', models.PositiveIntegerField()),
                ('packaging', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PromotionsEco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.CharField(max_length=200)),
                ('familleProduit', models.CharField(max_length=200)),
                ('descriptionProduit', models.CharField(max_length=200)),
                ('quantiteMin', models.PositiveIntegerField()),
                ('packaging', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PromotionsMag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.CharField(max_length=200)),
                ('familleProduit', models.CharField(max_length=200)),
                ('descriptionProduit', models.CharField(max_length=200)),
                ('quantiteMin', models.PositiveIntegerField()),
                ('packaging', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Promotions',
        ),
    ]
