# Generated by Django 2.2.6 on 2019-10-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_auto_20191008_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='lastName',
            new_name='Nom',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='account',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='fidelityPoint',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='payment',
        ),
        migrations.AddField(
            model_name='customers',
            name='Compte',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customers',
            name='Credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='customers',
            name='IdClient',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customers',
            name='Paiement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customers',
            name='Prenom',
            field=models.CharField(default='', max_length=200),
        ),
    ]
