# Generated by Django 2.2.6 on 2019-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_auto_20191008_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='exclusivite',
            field=models.CharField(default='', max_length=200),
        ),
    ]
