# Generated by Django 2.2.6 on 2019-10-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_products_exclusivite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='carteFid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='customers',
            name='IdClient',
            field=models.TextField(),
        ),
    ]
