# Generated by Django 2.2.6 on 2019-10-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_auto_20191016_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionseco',
            name='prixOriginel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotionseco',
            name='reduction',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotionsmag',
            name='prixOriginel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotionsmag',
            name='reduction',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
